[project]
name = "steam-meter"
version = "0.1.0"
description = "A Chrome extension that performs sentiment analysis on Steam reviews!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.1",
    "numpy>=2.3.3",
]
